name: Deploy to DigitalOcean

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy via SSH
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.DO_HOST }}
          username: ${{ secrets.DO_USER }}
          key: ${{ secrets.DO_SSH_KEY }}
          script: |
            cd /opt/athena

            # Pull latest code
            git pull origin main

            # Build and restart containers
            docker compose -f compose.prod.yml --env-file .env.prod up -d --build

            # delete old images
            docker image prune -f